import { APP_INITIALIZER, ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import {
  LucideAngularModule,
  Home,
  BarChart2,
  Building2,
  Info,
  FileText,
  Wrench,
  LogOut,
  Pencil,
  CheckSquare,
  Plus,
  Users,
  Crown,
  Clock,
  Circle,
  CheckCircle2,
  MoreHorizontal,
  Check,
  Trash2,
  Receipt,
  ArrowRight,
  FileCheck,
  FileX,
  Upload,
  Download,
  Eye,
  EyeOff,
  TriangleAlert,
  MessageSquare,
  UserCheck,
  ShieldCheck,
  Wallet,
  UserPlus,
  ChevronRight,
  Sparkles,
  Menu,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/auth/auth.interceptor';
import { AuthService } from './core/auth/auth.service';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        Home,
        BarChart2,
        Building2,
        Info,
        FileText,
        Wrench,
        LogOut,
        Pencil,
        CheckSquare,
        Plus,
        Users,
        Crown,
        Clock,
        Circle,
        CheckCircle2,
        MoreHorizontal,
        Check,
        Trash2,
        Receipt,
        ArrowRight,
        FileCheck,
        FileX,
        Upload,
        Download,
        Eye,
        EyeOff,
        TriangleAlert,
        MessageSquare,
        UserCheck,
        ShieldCheck,
        Wallet,
        UserPlus,
        ChevronRight,
        Sparkles,
        Menu,
        X,
      }),
    ),
    // wacht op auth init voor de router begint te navigeren
    {
      provide: APP_INITIALIZER,
      useFactory: (authService: AuthService) => () => authService.init(),
      deps: [AuthService],
      multi: true,
    },
  ],
};
